name    'LarsFronius-nginx'
version '0.0.3'
source 'https://github.com/LarsFronius/puppet-nginx.git'
author 'LarsFronius'
license 'APACHE2'
summary 'Basic module for configuring nginx via puppet'
description 'Basic module for configuring nginx via puppet. You can easily create fcgi or passenger vhost with this module.'
project_page 'http://github.com/LarsFronius/puppet-nginx'
